#!/bin/sh

# Based on the Nix install script
# This script installs Nix, Cachix and Dapptools

{ # Prevent execution if this script was only partially downloaded

  set -e
  
  oops() {
    echo >&2 "${0##*/}: error:" "$@"
    exit 1
  }

  if [ "$(id -u)" -eq 0 ]; then
    oops "please run this script as a regular user"
  fi

  if [ -z "$HOME" ]; then
    oops "\$HOME is not set"
  fi

  if [ -z "$USER" ]; then
    oops "\$USER is not set"
  fi

  have() { command -v "$1" >/dev/null; }

  # We don't handle NixOS yet
  { have nixos-version; } && {
    echo >&2 "We love that you are running NixOS! <3"
    echo >&2 "We're working on having this script work on NixOS, but for the moment"
    echo >&2 "go to https://dapp.tools and follow manual installation instructions."
    exit 1
  }

  # We need Nix v2
  { have nix; } || {
    echo >&2 "Please install Nix v2 before running this script"
    echo >&2 "You can run \`curl -sS https://nixos.org/nix/install | sh\`"
    exit 1
  }

  { have git; } || oops "you need to install Git before running this script"

  if [ ! -d "$HOME/.config/nix" ]; then
    mkdir -p "$HOME/.config/nix"
  fi

  if ! grep -q -F '# added by Dapptools installer' "$HOME/.config/nix/nix.conf"; then
    echo "Adding Cachix binary cache to Nix"
    cat <<EOF > "$HOME/.config/nix/nix.conf"
# added by Dapptools installer
substituters = https://cache.nixos.org https://dapp.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= dapp.cachix.org-1:9GJt9Ja8IQwR7YW/aF0QvCa6OmjGmsKoZIist0dG+Rs=
EOF
  fi

  dest="$HOME/.dapp/"

  if [ ! -d "$dest/dapptools" ]; then
    echo "Downloading dapptools..."
    mkdir -p "$dest"
    cd "$dest"
    git clone https://github.com/dapphub/dapptools --recursive --quiet
    echo "Done."
  fi

  cd "$dest/dapptools" || {
    oops "could not download dapptools!"
  }

  git submodule update --init --remote --quiet
  git pull --quiet

  echo "Installing dapptools... (this will take a while)"
  nix-env -f . -iA dapp seth solc hevm ethsign

  # Finished!
  cat <<EOF

Installation finished!

You now have access to dapp, seth, solc, hevm and ethsign.
EOF

} # End of wrapping
